---
- name: "add docker repository"
  shell: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"

- name: "install docker-ce"
  shell: "dnf install docker-ce --nobest -y"

- name: "start&enable docker daemon"
  systemd:
    name: docker
    state: started
    enabled: yes
